[package]
name = "UserDiscoveryService"
version = "0.0.1"
edition = "2021"

[dependencies]
http-body-util = "0.1.2"
json = "0.12.4"
serde = {version= "1.0.217", features = ["derive"]}
serde_json = "1.0.138"
anyhow = "1.0"
urlencoding = "2.1.3"
